Add files via upload
PiotrMaciejKowalski/BigData2024Project pull request #1
Opened 2023-10-23 20:07 UTC by PatrycjaRekorajska

2023-10-30 12:01 UTC, PiotrMaciejKowalski commented
Do repozytorium poza ostatecznością nie wpychamy plików z danymi oraz rzeczy różnych od kodów i konfiguracji.
Zrób proszę następujące rzeczy.
Załóż w repozytorium katalogi
* `dataset_reasearch`
* `dataset_research/NASA`
Następnie załóż plik 
* `dataset_research/NASA/research_summary.md`

Plik z danymi umieść na wspólnym drive i opisz w pliku jego lokalizację. Opisz co dowiedziałaś się o Datasetcie NASY. 
Jeśli masz jakiś kod do pierwszego testu danych wrzuć go do `dataset_research/NASA/src`. Skopiuj do niego informację o kolumnach i co się o nich dowiedziałaś. Ten pdf jest niepotrzebny jako element w repo. Możesz natomiast dać do pliku informację o urlu pod jakim można go znaleźć.

Pliki csv i pdf usuń z repo. Nie powinno ich być w tym Pull Requestcie (PR)

2023-10-30 12:02 UTC, PiotrMaciejKowalski requested changes
Zgodnie z komentarzem proszę o poprawki.

2023-10-31 20:05 UTC, PiotrMaciejKowalski commented
Nie widzę, żadnych zmian po moim review.

2023-10-31 20:18 UTC, PiotrMaciejKowalski requested changes

2023-11-02 17:32 UTC, PatrycjaRekorajska commented on dataset_research/NASA/research_summary.md
> +Zbior danych w formacie csv znajduję się na wspólnym drive w lokalizacj: https://drive.google.com/drive/u/1/folders/1tLGM4LURHCXctHuTUSmO_kr3JCzJJSPS
Mógłby Pan bardziej sprecyzować o co chodzi ze ścieżką we wspólnym repo?

2023-11-02 17:37 UTC, PiotrMaciejKowalski requested changes

2023-11-02 17:37 UTC, PiotrMaciejKowalski commented on dataset_research/NASA/research_summary.md
> +Zbior danych w formacie csv znajduję się na wspólnym drive w lokalizacj: https://drive.google.com/drive/u/1/folders/1tLGM4LURHCXctHuTUSmO_kr3JCzJJSPS
To jest link do współdzielonego pliku a gdrive. Ale kiedy wykonujemy przetwarzanie danych na colabie montujemy sobie nasz gdrive jako lokalny katalog. Wtedy scieżka ta wyglądać powinna 
`My Drive/katalog/plik1.csv`. 

Ale wiesz Patrycja - cofam to. Niech już będzie ten dataset pod linkiem. Popraw literówki i dodaj # dla tytułów sekcji.

2023-11-03 09:08 UTC, PiotrMaciejKowalski approved these changes

2023-11-03 09:08 UTC, PiotrMaciejKowalski commented on dataset_research/NASA/research_summary.md
> +* Prezentacja danych w formie miesięcznych podsumowań (srednie, sumy).
```suggestion
* Prezentacja danych w formie miesięcznych podsumowań (średnie, sumy).
```

2023-11-03 14:57 UTC, merged