tutorial Regex
PiotrMaciejKowalski/BigData2024Project pull request #12
Opened 2023-11-06 13:45 UTC by GitMariusz

2023-11-06 13:45 UTC, PiotrMaciejKowalski commented
Task linked: [CU-86bw7kz92 Materiał z Regex](https://app.clickup.com/t/86bw7kz92)

2023-11-08 16:53 UTC, PiotrMaciejKowalski requested changes

2023-11-08 16:53 UTC, PiotrMaciejKowalski commented on tutoriale/regex.md
> +### 1. Klasy znaku
kazdy hash odpowiada jednemu zagniezdzeniu. Więc nie przeskakujemy z poziomu 1 do 3 od razu

2023-11-08 16:54 UTC, PiotrMaciejKowalski commented on tutoriale/regex.md
> +### 1. Klasy znaku
ten zarzut powtarza sie tez niżej

2023-11-08 19:14 UTC, GitMariusz commented on tutoriale/regex.md
> +### 1. Klasy znaku
Poprawione

2023-11-10 14:53 UTC, PiotrMaciejKowalski approved these changes

2023-11-10 16:17 UTC, merged