Draft - drzewa decyzyjne
PiotrMaciejKowalski/BigData2024Project pull request #33
Opened 2023-12-27 15:42 UTC by RafalGwizdon

2023-12-29 07:19 UTC, PiotrMaciejKowalski requested changes
Dużo dobrych rzeczy na pokładzie. Mamy użycie datasetu anotowanego, Mamy model drzewiasty okey.
1. Pojawia się komenda (spark_NASA_sample_all.count() -> 1200) nie mamy tylu zaanotowanych przykładów. Skąd ten nadmiar. Podejrzewam duplikację wierszy i przy losowaniu train-test mamy wtedy przeciek do testu. (model w train miał już te same dane). Powinno byłobyć ograniczenie do jednego miesiąca dla danych.
2. Powinieneś mieć dwa modele albo 3 modele. 1 detekcja pustynia - niepustynia. 2 detekcja pustynia-step-inne 3. detekcja step - niestep.
3. Brakuje statystyk dla uczenia na zbalansowanym (balansowanie jest na plus)

2023-12-29 18:41 UTC, RafalGwizdon commented
> Dużo dobrych rzeczy na pokładzie. Mamy użycie datasetu anotowanego, Mamy model drzewiasty okey.
> 
> 1. Pojawia się komenda (spark_NASA_sample_all.count() -> 1200) nie mamy tylu zaanotowanych przykładów. Skąd ten nadmiar. Podejrzewam duplikację wierszy i przy losowaniu train-test mamy wtedy przeciek do testu. (model w train miał już te same dane). Powinno byłobyć ograniczenie do jednego miesiąca dla danych.
> 2. Powinieneś mieć dwa modele albo 3 modele. 1 detekcja pustynia - niepustynia. 2 detekcja pustynia-step-inne 3. detekcja step - niestep.
> 3. Brakuje statystyk dla uczenia na zbalansowanym (balansowanie jest na plus)

Ad 1. Wtedy użyłem 100 danych do lokalizacji dla każdego miesiąca od *pazdziernika 2022* do  *wrzesnia 2023*, teraz tylko z lipca 2023.
Ad 2. Powstały trzy modele.
Ad 3. Balansuje próbkę testową i na tak zbalansowanej znowu testuje.

2023-12-30 18:41 UTC, PiotrMaciejKowalski commented
Nie balansuj próbki testowej - to nie daje nic dobrego.

2023-12-31 10:49 UTC, RafalGwizdon commented
> Nie balansuj próbki testowej - to nie daje nic dobrego.

poprawiono

2024-01-04 19:29 UTC, PiotrMaciejKowalski approved these changes

2024-01-07 09:28 UTC, merged