Zadanie1 iza
PiotrMaciejKowalski/BigData2024Project pull request #5
Opened 2023-10-30 23:58 UTC by maria3magdalena

2023-10-31 03:33 UTC, PiotrMaciejKowalski requested changes

2023-10-31 03:33 UTC, PiotrMaciejKowalski commented on colabs/preprocessing.ipynb
> +{
Te rzeczy bym przeniósł do katalogu `code examples/colabs`. To w końcu nie są 'nasze' ładowania danych

2023-10-31 03:33 UTC, PiotrMaciejKowalski commented on notebooks/Wczytanie_danych.ipynb
> +{
to samo dla plików z notebooks. przeniesć do `code examples/notebooks`.

2023-10-31 03:33 UTC, PiotrMaciejKowalski commented on stripped/Wczytanie_danych_stripped.py
> +#!/usr/bin/env python
Ten plik usunąć.

2023-10-31 03:33 UTC, PiotrMaciejKowalski commented on tutoriale/Get Started with Pytest.md
> +![img](pytest_files/pytest1.png)
To są linki do obrazków - ale nie widzę tych plików w naszym repo.
Jak kraść - to brać całe kolekcje :-)

2023-10-31 03:33 UTC, PiotrMaciejKowalski commented on tutoriale/Get Started with Pytest.md
> +> Za **dobrą praktykę** tworzenia testów uważa się kolejność: *napisanie testu &rarr; uruchomienie testu z oczekiwanym błędem &rarr; poprawienie aplikacji &rarr; ponowne uruchomienie testu z oczekiwa
Tu coś jest nie tak z markdownem.

2023-10-31 03:33 UTC, PiotrMaciejKowalski commented on tutoriale/Jak korzystac z GitHub.md
> +    ![](images/clickup1.jpg)
Też linki do nieistniejących plików.

2023-10-31 03:33 UTC, PiotrMaciejKowalski commented on tutoriale/Jak korzystac z GitHub.md
> +# Przydatne komendy gitowe
Szukałaś materiału do swojego tutoriala o gitcie? Tu jest sporo

2023-10-31 03:33 UTC, PiotrMaciejKowalski commented on tutoriale/setup_sparka.sh
> +pip install pyspark py4j
Przenieść cały plik do `code examples/bash scripts`

2023-11-03 20:30 UTC, maria3magdalena commented on tutoriale/Get Started with Pytest.md
> +> Za **dobrą praktykę** tworzenia testów uważa się kolejność: *napisanie testu &rarr; uruchomienie testu z oczekiwanym błędem &rarr; poprawienie aplikacji &rarr; ponowne uruchomienie testu z oczekiwa
Chodzi o niepotrzebne cytowanie...?

2023-11-04 10:26 UTC, PiotrMaciejKowalski approved these changes

2023-11-04 10:26 UTC, merged