Uploded
PiotrMaciejKowalski/BigData2024Project pull request #50
Opened 2024-01-27 17:31 UTC by GitMariusz

Próbowałem robić k-średnich z t-SNE, hierarchiczne grupowanie ale się nie udawało albo wyniki nie były lepsze od pozostałych modeli. Ostatecznie spróbowałem zrobić grupowanie za pomocą algorytmu Brich. Wydaje mi się, że te modele nie mają szans przebić wyników otrzymanych z lasów losowych z danymi uśrednionymi lub nawet zwykłych drzew losowych. W związku z czym nie wiem czy warto jest kontynuować prace nad algorytmami grupującymi.

2024-01-28 10:24 UTC, PiotrMaciejKowalski commented
@maria3magdalena  Iza - zrób proszę wstępne review.

2024-01-28 10:29 UTC, PiotrMaciejKowalski commented
@RafalRozycki ty też spójrz proszę do review tego.

2024-01-29 15:34 UTC, maria3magdalena reviewed
Chyba trochę brakuje mi map dla grupowania na calym datasecie? Są praktycznie tylko mapy dla zbioru anotowanego (poza jedną, która umieszczona jest w sekcji poświęconej algorytmom, które "nie wypaliły", być może przez pomyłkę?)

2024-01-29 15:34 UTC, maria3magdalena commented on stripped/colabs/Birch_stripped.py
> +def do_kmeans_with_tsne_return_preds(list_of_scaled_df: List, n_components: int=2, perplexity:float=30, learning_rate: Union[float, str]="auto", n_clusters: int=2, random_state: int=123) -> List:
Typing dla list_of_scaled_df to chyba List[pd.DataFrame] ? Btw. Może lepiej byłoby, żeby funkcja robiła to co robi dla pojedynczego dataframe a nie całej listy dataframe'ów? (i potem zastosowac ja dla poszczególnych df)

2024-01-29 15:34 UTC, maria3magdalena commented on stripped/colabs/Birch_stripped.py
> +list_of_df = [nasa_202210, nasa_202304, nasa_202305, nasa_202306, nasa_202307, nasa_202308, nasa_202309]
Niepotrzebnie dublujemy sie, dokladnie ta sama zmienna była juz utworzona wcześniej

2024-01-29 15:34 UTC, maria3magdalena commented on stripped/colabs/Birch_stripped.py
> +show(plot_map(df=nasa_202307, parameter_name='Cluster', colormap=colormap_cluster, title="Predykce", alpha=0.5))
Literówka w tytule mapy. Nie rozumiem dlaczego "drukujemy" mapę z wynikami birch, skoro linijke wczesniej robiles hierarchical clustering? To pomyłka?

2024-01-29 15:34 UTC, maria3magdalena commented on stripped/colabs/Birch_stripped.py
> +  list_of_scaled_df.append(X_scaled)
Chyba się dublujemy tutaj niepotrzebnie? Czy to ta sama list_of_df co wcześniej? (nie widzę innej)

2024-01-29 15:34 UTC, maria3magdalena commented on stripped/colabs/Birch_stripped.py
> +# * Grupowanie hierarchiczne dla parametrów linkage: "ward", "average", "complete" nie powiodło się ponieważ na Colabie jest zbyt mała pamięć RAM i za każdym razem usuwało sesję. Grupowanie to zadzia
W twoim pliku widzę wyniki klastrowania dla linkage='ward'. Czyli rozumiem, że to jednak dla "ward" się przeliczyło (choć wrzuciło do drugiego klastra tylko jeden elment), a nie dla "single"? 😉 Bo w notatniku nie ma wyników klastrowania dla linkage='single'....

2024-01-29 20:49 UTC, RafalRozycki commented on stripped/colabs/Birch_stripped.py
> +nasa_202309 = load_single_month(spark, year=2023, month=9).toPandas()
Stąd chyba zostały usunięte dwa DataFrame'y, co powoduje, że listed_of_merged_df jest 5-elementowy, zaś predykcje_df oczekują 7.

2024-02-01 01:58 UTC, PiotrMaciejKowalski requested changes

2024-02-01 01:58 UTC, PiotrMaciejKowalski commented on stripped/colabs/Birch_stripped.py
> +#%cd ..
To część szablonu - ja bym zostawił.

2024-02-01 01:58 UTC, PiotrMaciejKowalski commented on stripped/colabs/Birch_stripped.py
> +def StandardScaling(df: pd.DataFrame, attributes: list) -> pd.DataFrame:
Problemem jest, że 'lon' i 'lat' są potrzebne do wizualizacji. Robiąc ograniczenie w transformacjach łatwo będzie Mariuszowi je zgubić do czasu gdy będzie ich potrzebował do wykresu. Problem 'disallowed columns' w modelach nie ma jednoznacznego dobrego rozwiązania w kodzie. Na tym poziomie kodzenia dla mnie jest akceptowalne konsekwentne obcinanie się do wybranych attributes.

2024-02-01 01:58 UTC, PiotrMaciejKowalski commented on stripped/colabs/Birch_stripped.py
> +def MinMaxScaling(df: pd.DataFrame, attributes: list) -> pd.DataFrame:
j/w moja uwaga.

2024-02-01 01:58 UTC, PiotrMaciejKowalski commented on stripped/colabs/Birch_stripped.py
> +  list_of_scaled_df.append(X_scaled)
Appendowanie list jest faktycznie mniej czytelne od comprehension listy. Ale polecam je ładniej dzielić między liniami
```
[
wartosc
for wartosc
in kolekcja
]
```

2024-02-01 01:58 UTC, PiotrMaciejKowalski commented on stripped/colabs/Birch_stripped.py
> +  list_of_scaled_df.append(X_scaled)
To samo co napisałem Ci na teamsach. MinMax(Standard()) nie ma dla mnie sensu. To po prostu MinMax

2024-02-01 01:58 UTC, PiotrMaciejKowalski commented on stripped/colabs/Birch_stripped.py
> +  birch_results = birch_model.predict(scaled_df.loc[:,'Rainf':'SoilM_100_200cm'])
użyć `fit_predict`

2024-02-01 01:58 UTC, PiotrMaciejKowalski commented on stripped/colabs/Birch_stripped.py
> +    print("F1-score: ", round(f1_score(merged_df["pustynia_i_step"], birch_results)*100, 2))
Można zastapic przez `sklearn.metrics.classification_report`

2024-02-01 01:58 UTC, PiotrMaciejKowalski commented on stripped/colabs/Birch_stripped.py
> +birch_results = birch_model.predict(merged_df.loc[:,'Rainf':'SoilM_100_200cm'])
`fit_predict`

2024-02-01 01:58 UTC, PiotrMaciejKowalski commented on stripped/colabs/Birch_stripped.py
> +merged_df["Cluster"] = birch_results
można połączyć z tym wyżej i wywalić zmienną

2024-02-01 02:00 UTC, PiotrMaciejKowalski commented
Tak jak w wiadomości. Według mnie podziel notatnik na dwa. Jeden taki jaki jest przenieś do archive. A w kopii ogranicz się do bircha i tam popraw detale i prezentuj na demo.

2024-02-01 02:01 UTC, PiotrMaciejKowalski commented
@maria3magdalena dzięki za uwagi do całości notatnika. @GitMariusz choć tamte uwagi są cenne, te które dotyczą rzeczy których nie będziesz demować możesz nie poprawiać.

2024-02-01 02:11 UTC, maria3magdalena commented on stripped/colabs/Birch_stripped.py
> +def StandardScaling(df: pd.DataFrame, attributes: list) -> pd.DataFrame:
Tyle, że ta funkcja Mariusza i tak koniec końców obcina kolumny 'lon' i 'lat' , i zwraca dataframe bez tych kolumn, więc to, że przekazujemy do funkcji cały dataframe, nic nam tutaj nie daje... (Dalej, po użyciu tej funkcji, Mariusz w swoim notatniku "domergowuje" te kolumny).

2024-02-04 08:57 UTC, PiotrMaciejKowalski approved these changes

2024-02-04 10:32 UTC, merged