Wikipedia
PiotrMaciejKowalski/BigData2024Project pull request #6
Opened 2023-10-31 19:26 UTC by RafalGwizdon

2023-10-31 20:20 UTC, PiotrMaciejKowalski requested changes

2023-10-31 20:20 UTC, PiotrMaciejKowalski commented on Wikipedia_do_CSV.md
> +Źródło danych: https://dumps.wikimedia.org/plwiki/20231001/ \\
poprawić linki według materiału [https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

2023-10-31 20:20 UTC, PiotrMaciejKowalski commented on Wikipedia_do_CSV.md
> +#Łączenie plików CSV
Brak spacji

2023-10-31 20:20 UTC, PiotrMaciejKowalski commented on Wikipedia_do_CSV.md
> +#Pobieranie danych z Wikipedii
Spacja brakuje

2023-10-31 20:20 UTC, PiotrMaciejKowalski commented on Wikipedia_do_CSV.md
> +Program powstał w celu zaimportowania danych z Polskiej Wikipedii i zapisaniu ich w pliku csv. \\
Znaki nowych linii nie są potrzebne

2023-10-31 20:22 UTC, PiotrMaciejKowalski commented
Naprawdę małe detale. I będziemy mogli zamknąć.

Trochę by się prosiło o zrobienia notatnika Jupytera zamiast markdowna - no ale skoro to był kod do wykonania na raz - ujdzie.

2023-11-03 18:17 UTC, RafalGwizdon commented
Poprawiłem wskazane błędy.

2023-11-04 10:28 UTC, PiotrMaciejKowalski approved these changes

2023-11-04 14:09 UTC, merged